# Generated by Django 5.1.15 on 2026-09-18 00:28

import app.core.fields
import app.models.user
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(db_index=True, unique=True, verbose_name='Número de Box')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible para Llamado'), ('En Atencion', 'En Atención con Paciente'), ('Fuera de servicio', 'Fuera de Servicio / Cerrado')], default='Fuera de servicio', max_length=30, verbose_name='Estado Operativo del Box')),
                ('activo', models.BooleanField(default=True, verbose_name='Box Habilitado / Activo')),
                ('discapacidad', models.BooleanField(db_index=True, default=False, verbose_name='Habilitado para Discapacidad / Movilidad Reducida')),
            ],
            options={
                'verbose_name': 'Box de Atención',
                'verbose_name_plural': 'Boxes de Atención',
                'db_table': 'sgtp_box',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_practica', models.CharField(max_length=50, unique=True, verbose_name='Código Único de Práctica')),
                ('nombre', models.CharField(db_index=True, max_length=255, verbose_name='Nombre / Descripción del Estudio')),
                ('tipo_muestra', models.CharField(choices=[('Sangre', 'Muestra Sanguínea'), ('Orina', 'Muestra de Orina'), ('Hisopado', 'Hisopado Nasofaríngeo / Fauces'), ('LCR', 'Líquido Cefalorraquídeo'), ('Materia Fecal', 'Materia Fecal'), ('Otro', 'Otro Tipo de Muestra')], default='Sangre', max_length=50, verbose_name='Tipo de Muestra Requerida')),
                ('activo', models.BooleanField(default=True, verbose_name='Práctica Habilitada / Activa')),
            ],
            options={
                'verbose_name': 'Estudio Médico',
                'verbose_name_plural': 'Catálogo de Estudios Médicos',
                'db_table': 'sgtp_estudios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialReporteDiario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reporte', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('total_pacientes_atendidos', models.IntegerField(default=0)),
                ('total_estudios_realizados', models.IntegerField(default=0)),
                ('destinatarios_notificados', models.TextField(help_text='Lista de emails a los que se remitió el reporte')),
                ('fecha_hora_envio', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('error_detalle', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Historial de Reporte Diario',
                'verbose_name_plural': 'Historial de Reportes Diarios',
                'db_table': 'sgtp_historial_reportes',
                'ordering': ['-fecha_hora_envio'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica si el registro fue borrado lógicamente del sistema.')),
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField(db_index=True, unique=True, verbose_name='Documento Nacional de Identidad')),
                ('num_obra_social', app.core.fields.FernetEncryptedCharField(max_length=512, verbose_name='Número de Obra Social / Cobertura Médica (Cifrado FLE)')),
                ('nombre', app.core.fields.FernetEncryptedCharField(max_length=512, validators=[app.models.user.validar_solo_letras_min2], verbose_name='Nombre(s) (Cifrado FLE)')),
                ('apellidos', app.core.fields.FernetEncryptedCharField(max_length=512, validators=[app.models.user.validar_solo_letras_min2], verbose_name='Apellido(s) (Cifrado FLE)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Alta en Sistema')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'sgtp_paciente',
                'ordering': ['dni'],
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_personal', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico Institucional')),
                ('nombre', models.CharField(max_length=150, validators=[app.models.user.validar_solo_letras_min2], verbose_name='Nombre(s)')),
                ('apellidos', models.CharField(max_length=150, validators=[app.models.user.validar_solo_letras_min2], verbose_name='Apellido(s)')),
                ('dni', models.IntegerField(unique=True, verbose_name='Documento Nacional de Identidad')),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula Profesional')),
                ('rol', models.CharField(choices=[('Admin', 'Administrador General'), ('Jefa', 'Jefa de Laboratorio / Triage'), ('Admision', 'Operador de Admisión'), ('Box', 'Técnico / Bioquímico de Box'), ('Secretaria', 'Secretaría')], max_length=20, verbose_name='Rol Operativo')),
                ('activo', models.BooleanField(default=True, verbose_name='Estado de Actividad / Habilitado')),
                ('cant_intentos', models.IntegerField(default=0, verbose_name='Intentos Fallidos de Inicio de Sesión')),
                ('inicio_turno', models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio de Turno Laboral')),
                ('fin_turno', models.TimeField(blank=True, null=True, verbose_name='Hora de Finalización de Turno Laboral')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acceso al Panel Administrativo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal Hospitalario',
                'db_table': 'sgtp_personal',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='HabilitacionHoraria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('motivo', models.CharField(max_length=255)),
                ('activa', models.BooleanField(default=True)),
                ('aprobado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habilitaciones_otorgadas', to=settings.AUTH_USER_MODEL)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilitaciones_horarias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Habilitación Horaria Excepcional',
                'verbose_name_plural': 'Habilitaciones Horarias Excepcionales',
                'db_table': 'sgtp_habilitacion_horaria',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica si el registro fue borrado lógicamente del sistema.')),
                ('id_ticket', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador Universal del Ticket')),
                ('num_totem', models.CharField(db_index=True, max_length=50, verbose_name='Número Manual Tótem / Externo')),
                ('fecha_hora_admision', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora de Admisión (UTC)')),
                ('clasificacion_triage', models.CharField(choices=[('Guardia', 'Guardia / Urgencia Inmediata'), ('Medicos', 'Médicos / Personal Sanitario'), ('discapacidad', 'Discapacidad / Movilidad Reducida'), ('Oncologia', 'Pacientes Oncológicos'), ('Extraccion con Turno', 'Extracción con Turno Previo'), ('Extraccion sin Turno', 'Extracción Espontánea sin Turno'), ('Otro', 'Otro Tipo de Atención')], db_index=True, max_length=40, verbose_name='Clasificación de Triage Asistencial')),
                ('justificacion_otro', models.TextField(blank=True, null=True, verbose_name="Justificación médica (Obligatoria si triage='Otro')")),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente en Sala de Espera'), ('En Atencion', 'En Atención en Box'), ('Finalizado', 'Atención Finalizada'), ('Cancelado', 'Ticket Cancelado / Ausente')], db_index=True, default='Pendiente', max_length=30, verbose_name='Estado de Atención del Ticket')),
                ('box_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_atendidos', to='app.box', verbose_name='Box que está atendiendo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='app.paciente', verbose_name='Paciente Asociado')),
                ('personal_admision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_admitidos', to=settings.AUTH_USER_MODEL, verbose_name='Operador de Admisión')),
            ],
            options={
                'verbose_name': 'Ticket de Atención',
                'verbose_name_plural': 'Tickets de Atención',
                'db_table': 'sgtp_ticket',
                'ordering': ['fecha_hora_admision'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionesBox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo_cierre', models.CharField(blank=True, choices=[('Finalizado', 'Atención Finalizada Satisfactoriamente'), ('Derivado', 'Paciente Derivado a Otro Servicio'), ('Cancelado', 'Atención Cancelada / Paciente no Respondió'), ('Reasignado', 'Reasignado a Otro Box')], max_length=40, null=True, verbose_name='Motivo de Finalización o Cierre de Atención')),
                ('fecha_hora_inicio', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora de Inicio (UTC)')),
                ('fecha_hora_final', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Finalización (UTC)')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_box', to=settings.AUTH_USER_MODEL, verbose_name='Técnico / Profesional a Cargo')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='app.box', verbose_name='Box Utilizado')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_historial', to='app.ticket', verbose_name='Ticket Asistido')),
            ],
            options={
                'verbose_name': 'Asignación de Box',
                'verbose_name_plural': 'Historial de Asignaciones de Box',
                'db_table': 'sgtp_asignaciones_box',
                'ordering': ['-fecha_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TicketEstudios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='Solicitado', max_length=50, verbose_name='Estado de la Práctica')),
                ('observaciones', models.CharField(blank=True, default='', max_length=255, verbose_name='Observaciones Específicas')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_asociados', to='app.estudios', verbose_name='Estudio / Práctica Médica')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='app.ticket', verbose_name='Ticket Asociado')),
            ],
            options={
                'verbose_name': 'Estudio de Ticket',
                'verbose_name_plural': 'Estudios de Tickets',
                'db_table': 'sgtp_ticket_estudios',
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado', 'clasificacion_triage', 'fecha_hora_admision'], name='sgtp_ticket_estado_51fb11_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketestudios',
            unique_together={('ticket', 'estudio')},
        ),
    ]
