# Generated by Django 5.1.15 on 2026-09-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='personal',
            name='rol',
            field=models.CharField(choices=[('Admin', 'Administrador General'), ('Jefa', 'Jefa de Laboratorio / Triage'), ('Admision', 'Operador de Admisión'), ('Box', 'Técnico de Box'), ('Secretaria', 'Secretaría')], max_length=20, verbose_name='Rol Operativo'),
        ),
    ]
