# Generated by Django 5.1.15 on 2026-09-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_personal_groups_remove_personal_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='apellidos',
            field=models.CharField(max_length=150, verbose_name='Apellido(s)'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre(s)'),
        ),
    ]
