# Generated by Django 5.1.15 on 2026-09-24 06:38

import app.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_personal_apellidos_alter_personal_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudios',
            name='seccion',
            field=models.CharField(choices=[('Bactereologia', 'Bactereología'), ('quimica', 'Química'), ('IAC', 'IAC'), ('Endocrinologia', 'Endocrinología'), ('Marcadores oncologicos', 'Marcadores Oncológicos'), ('serologia', 'Serología'), ('varios', 'Varios'), ('orina', 'Orina'), ('hematologia', 'Hematología'), ('parasitologia', 'Parasitología'), ('determinaciones especiales', 'Determinaciones Especiales'), ('toxicologia', 'Toxicología')], default='varios', max_length=50, verbose_name='Sección del Estudio'),
        ),
        migrations.AlterField(
            model_name='estudios',
            name='nombre',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nombre  del Estudio'),
        ),
        migrations.AlterField(
            model_name='estudios',
            name='tipo_muestra',
            field=models.CharField(choices=[('edta', 'EDTA'), ('citrato', 'Citrato'), ('orina', 'Orina'), ('materia fecal', 'Materia Fecal'), ('jeringa', 'Jeringa'), ('suero', 'Suero'), ('otro', 'Otro')], default='otro', max_length=50, verbose_name='Tipo de Muestra Requerida'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='apellidos',
            field=models.CharField(max_length=150, validators=[app.core.validators.validar_solo_letras_min2], verbose_name='Apellido(s)'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='nombre',
            field=models.CharField(max_length=150, validators=[app.core.validators.validar_solo_letras_min2], verbose_name='Nombre(s)'),
        ),
    ]
